# Generated by Django 6.1 on 2026-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='tag2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='tag3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
