# Generated by Django 6.1 on 2026-09-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_enrollment_completed_at_enrollment_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
