# Generated by Django 6.1 on 2026-09-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_payment_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='place',
        ),
    ]
